# Generated by Django 6.0.1 on 2026-01-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_du_an', models.CharField(max_length=200)),
                ('anh_mo_ta', models.ImageField(upload_to='projects/')),
                ('mo_ta_ngan', models.CharField(max_length=250)),
                ('noi_dung_chi_tiet', models.TextField()),
                ('cong_nghe_su_dung', models.CharField(help_text='Ví dụ: Python, Django, ReactJS', max_length=200)),
                ('link_demo', models.URLField(blank=True, help_text='Link web chạy thực tế')),
                ('link_source_code', models.URLField(blank=True, help_text='Link Github')),
            ],
        ),
        migrations.CreateModel(
            name='HoSo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_hien_thi', models.CharField(help_text='Tên bạn muốn hiện trên web', max_length=100)),
                ('nghe_nghiep', models.CharField(help_text='Ví dụ: Backend Developer', max_length=100)),
                ('gioi_thieu', models.TextField(help_text='Đoạn văn giới thiệu bản thân ngắn gọn')),
                ('avatar', models.ImageField(upload_to='profile_pics/')),
                ('file_cv', models.FileField(blank=True, help_text='File PDF CV để người xem tải về', upload_to='cv_files/')),
                ('link_github', models.URLField(blank=True)),
                ('link_linkedin', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThanhTich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200, verbose_name='Tên thành tích/Chứng chỉ')),
                ('to_chuc_cap', models.CharField(help_text='Ví dụ: Coursera, Google, Đại học Bách Khoa', max_length=200, verbose_name='Nơi cấp')),
                ('ngay_nhan', models.DateField()),
                ('mo_ta', models.TextField(blank=True, help_text='Mô tả kỹ hơn về độ khó của chứng chỉ này')),
                ('hinh_anh_chung_nhan', models.ImageField(blank=True, upload_to='certificates/')),
            ],
            options={
                'verbose_name_plural': 'Các Thành Tích',
                'ordering': ['-ngay_nhan'],
            },
        ),
    ]
